/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package ibd.query;

import java.util.Iterator;

/**
 * This class limits the number of tuples generated by an Operation Iterator. 
 * @author Sergio
 */
public class PagedOperationIterator extends OperationIterator {

    Iterator<Tuple> delegateIterator;
    int tuplesToRead;
    int startingTuple;
    int tuplesRead;
    
    
    public PagedOperationIterator(Iterator<Tuple> delegateIterator,int startingTupleIndex, int tuplesToRead){
        this.delegateIterator = delegateIterator;
        this.startingTuple = startingTupleIndex;
        this.tuplesToRead = startingTupleIndex + tuplesToRead;
        tuplesRead = 0;
    }

    @Override
    protected Tuple findNextTuple(){
        if (tuplesRead>=tuplesToRead)
            return null;
        
        Tuple tuple = null;
        while (tuplesRead<startingTuple){
            tuple = delegateIterator.next();
            if (tuple==null) break;
            tuplesRead++;
        }
        tuple = delegateIterator.next();
        tuplesRead++;
        
        return tuple;
    }

}
